### ISSUE TITLE
Missing products files

### ISSUE THREAD

**Issue by 0x24D** [33bca-archive/android_device_xiaomi_davinci#1]
Hello, I am currently trying to build an unofficial version of PA Quartz so that I can implement signature spoofing as it is not yet possible to patch Android 10 using Magisk, etc.

I am unable to complete the build as `pa_davinci.mk` and `pa.dependencies` are missing from https://github.com/AOSPA/android_vendor_pa/tree/quartz/products. Where am I able to find these files?

**Comment by 33bca** [comment]
Here you go: https://gerrit.aospa.co/c/AOSPA/android_vendor_pa/+/6618 ;D
